language: java

dist: trusty
sudo: required

git:
  depth: false

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}

before_install:
- rm -rf $HOME/.m2/repository/com/powsybl

install:
# Build powsybl-core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- pushd powsybl/powsybl-core && mvn --batch-mode -DskipTests install && popd

script:
- mvn clean test jacoco:report coveralls:report
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_JDK_VERSION" = "oraclejdk8" -a "$TRAVIS_SECURE_ENV_VARS"  = "true" ]; then mvn -B sonar:sonar; fi

before_cache:
- rm -rf $HOME/.m2/repository/com/powsybl