#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:DiscExcContIEEEDEC3A .
  OPTIONAL { ?id cim:DiscontinuousExcitationControlDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:DiscExcContIEEEDEC3A.tdr ?tdr . }
  OPTIONAL { ?id cim:DiscExcContIEEEDEC3A.vtmin ?vtmin . }
}
