#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcAC3A .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcAC3A.tr ?tr . }
  OPTIONAL { ?id cim:ExcAC3A.tb ?tb . }
  OPTIONAL { ?id cim:ExcAC3A.tc ?tc . }
  OPTIONAL { ?id cim:ExcAC3A.ka ?ka . }
  OPTIONAL { ?id cim:ExcAC3A.ta ?ta . }
  OPTIONAL { ?id cim:ExcAC3A.vamax ?vamax . }
  OPTIONAL { ?id cim:ExcAC3A.vamin ?vamin . }
  OPTIONAL { ?id cim:ExcAC3A.te ?te . }
  OPTIONAL { ?id cim:ExcAC3A.vemin ?vemin . }
  OPTIONAL { ?id cim:ExcAC3A.kr ?kr . }
  OPTIONAL { ?id cim:ExcAC3A.kf ?kf . }
  OPTIONAL { ?id cim:ExcAC3A.tf ?tf . }
  OPTIONAL { ?id cim:ExcAC3A.kc ?kc . }
  OPTIONAL { ?id cim:ExcAC3A.kd ?kd . }
  OPTIONAL { ?id cim:ExcAC3A.ke ?ke . }
  OPTIONAL { ?id cim:ExcAC3A.vfemax ?vfemax . }
  OPTIONAL { ?id cim:ExcAC3A.e1 ?e1 . }
  OPTIONAL { ?id cim:ExcAC3A.se1 ?se1 . }
  OPTIONAL { ?id cim:ExcAC3A.e2 ?e2 . }
  OPTIONAL { ?id cim:ExcAC3A.se2 ?se2 . }
}
