#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcDC2A .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcDC2A.tr ?tr . }
  OPTIONAL { ?id cim:ExcDC2A.ka ?ka . }
  OPTIONAL { ?id cim:ExcDC2A.ta ?ta . }
  OPTIONAL { ?id cim:ExcDC2A.tb ?tb . }
  OPTIONAL { ?id cim:ExcDC2A.tc ?tc . }
  OPTIONAL { ?id cim:ExcDC2A.vrmax ?vrmax . }
  OPTIONAL { ?id cim:ExcDC2A.vrmin ?vrmin . }
  OPTIONAL { ?id cim:ExcDC2A.ke ?ke . }
  OPTIONAL { ?id cim:ExcDC2A.te ?te . }
  OPTIONAL { ?id cim:ExcDC2A.kf ?kf . }
  OPTIONAL { ?id cim:ExcDC2A.tf ?tf . }
  OPTIONAL { ?id cim:ExcDC2A.efd1 ?efd1 . }
  OPTIONAL { ?id cim:ExcDC2A.seefd1 ?seefd1 . }
  OPTIONAL { ?id cim:ExcDC2A.efd2 ?efd2 . }
  OPTIONAL { ?id cim:ExcDC2A.seefd2 ?seefd2 . }
  OPTIONAL { ?id cim:ExcDC2A.exclim ?exclim . }
  OPTIONAL { ?id cim:ExcDC2A.vlb ?vlb . }
}
