#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcIEEEDC3A .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.trh ?trh . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.kv ?kv . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.vmax ?vmax . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.vmin ?vmin . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.ke ?ke . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.te ?te . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.kf ?kf . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.tf ?tf . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.efd1 ?efd1 . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.seefd1 ?seefd1 . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.efd2 ?efd2 . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.seefd2 ?seefd2 . }
  OPTIONAL { ?id cim:ExcIEEEDC3A.exclim ?exclim . }
}
