#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcNI .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcNI.busfedSelector ?busfedSelector . }
  OPTIONAL { ?id cim:ExcNI.ka ?ka . }
  OPTIONAL { ?id cim:ExcNI.ta ?ta . }
  OPTIONAL { ?id cim:ExcNI.tb ?tb . }
  OPTIONAL { ?id cim:ExcNI.te ?te . }
  OPTIONAL { ?id cim:ExcNI.vrmn ?vrmn . }
  OPTIONAL { ?id cim:ExcNI.vrmx ?vrmx . }
}
