#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcOEX3T .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcOEX3T.ka ?ka . }
  OPTIONAL { ?id cim:ExcOEX3T.ta ?ta . }
  OPTIONAL { ?id cim:ExcOEX3T.tb ?tb . }
  OPTIONAL { ?id cim:ExcOEX3T.tc ?tc . }
  OPTIONAL { ?id cim:ExcOEX3T.kc ?kc . }
  OPTIONAL { ?id cim:ExcOEX3T.kd ?kd . }
  OPTIONAL { ?id cim:ExcOEX3T.kf ?kf . }
  OPTIONAL { ?id cim:ExcOEX3T.tf ?tf . }
  OPTIONAL { ?id cim:ExcOEX3T.t1 ?t1 . }
  OPTIONAL { ?id cim:ExcOEX3T.t2 ?t2 . }
  OPTIONAL { ?id cim:ExcOEX3T.t3 ?t3 . }
  OPTIONAL { ?id cim:ExcOEX3T.t4 ?t4 . }
  OPTIONAL { ?id cim:ExcOEX3T.t5 ?t5 . }
  OPTIONAL { ?id cim:ExcOEX3T.t6 ?t6 . }
  OPTIONAL { ?id cim:ExcOEX3T.vrmax ?vrmax . }
  OPTIONAL { ?id cim:ExcOEX3T.vrmin ?vrmin . }
  OPTIONAL { ?id cim:ExcOEX3T.e1 ?e1 . }
  OPTIONAL { ?id cim:ExcOEX3T.se1 ?se1 . }
  OPTIONAL { ?id cim:ExcOEX3T.e2 ?e2 . }
  OPTIONAL { ?id cim:ExcOEX3T.se2 ?se2 . }
}
