#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcSYMPTR .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcSYMPTR.efmx ?efmx . }
  OPTIONAL { ?id cim:ExcSYMPTR.efmn ?efmn . }
  OPTIONAL { ?id cim:ExcSYMPTR.vopi ?vopi . }
  OPTIONAL { ?id cim:ExcSYMPTR.vres ?vres . }
  OPTIONAL { ?id cim:ExcSYMPTR.tr ?tr . }
  OPTIONAL { ?id cim:ExcSYMPTR.vrmax ?vrmax . }
  OPTIONAL { ?id cim:ExcSYMPTR.vrmin ?vrmin . }
}
