#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcSEXS .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcSEXS.tr ?tr . }
  OPTIONAL { ?id cim:ExcSEXS.tatb ?tatb . }
  OPTIONAL { ?id cim:ExcSEXS.tb ?tb . }
  OPTIONAL { ?id cim:ExcSEXS.k ?k . }
  OPTIONAL { ?id cim:ExcSEXS.te ?te . }
  OPTIONAL { ?id cim:ExcSEXS.emin ?emin . }
  OPTIONAL { ?id cim:ExcSEXS.emax ?emax . }
}
