#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovCT1 .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovCT1.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovCT1.r ?r . }
  OPTIONAL { ?id cim:GovCT1.rdown ?rdown . }
  OPTIONAL { ?id cim:GovCT1.rup ?rup . }
  OPTIONAL { ?id cim:GovCT1.ta ?ta . }
  OPTIONAL { ?id cim:GovCT1.tact ?tact . }
  OPTIONAL { ?id cim:GovCT1.tb ?tb . }
  OPTIONAL { ?id cim:GovCT1.tc ?tc . }
  OPTIONAL { ?id cim:GovCT1.teng ?teng . }
  OPTIONAL { ?id cim:GovCT1.tf ?tf . }
  OPTIONAL { ?id cim:GovCT1.tsa ?tsa . }
  OPTIONAL { ?id cim:GovCT1.tsb ?tsb . }
  OPTIONAL { ?id cim:GovCT1.vmax ?vmax . }
  OPTIONAL { ?id cim:GovCT1.vmin ?vmin . }
  OPTIONAL { ?id cim:GovCT1.wfnl ?wfnl . }
  OPTIONAL { ?id cim:GovCT1.wfspd ?wfspd . }
  OPTIONAL { ?id cim:GovCT1.kdgov ?kdgov . }
  OPTIONAL { ?id cim:GovCT1.kigov ?kigov . }
  OPTIONAL { ?id cim:GovCT1.kpgov ?kpgov . }
  OPTIONAL { ?id cim:GovCT1.kpload ?kpload . }
  OPTIONAL { ?id cim:GovCT1.kiload ?kiload . }
  OPTIONAL { ?id cim:GovCT1.tdgov ?tdgov . }
  OPTIONAL { ?id cim:GovCT1.tno ?tno . }
  OPTIONAL { ?id cim:GovCT1.ldref ?ldref . }
  OPTIONAL { ?id cim:GovCT1.dm ?dm . }
  OPTIONAL { ?id cim:GovCT1.db ?db . }
  OPTIONAL { ?id cim:GovCT1.ropen ?ropen . }
  OPTIONAL { ?id cim:GovCT1.rclose ?rclose . }
  OPTIONAL { ?id cim:GovCT1.kimw ?kimw . }
  OPTIONAL { ?id cim:GovCT1.pmwset ?pmwset . }
  OPTIONAL { ?id cim:GovCT1.aset ?aset . }
  OPTIONAL { ?id cim:GovCT1.ka ?ka . }
}
