#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovHydroIEEE0 .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovHydroIEEE0.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovHydroIEEE0.k ?k . }
  OPTIONAL { ?id cim:GovHydroIEEE0.t1 ?t1 . }
  OPTIONAL { ?id cim:GovHydroIEEE0.t2 ?t2 . }
  OPTIONAL { ?id cim:GovHydroIEEE0.t3 ?t3 . }
  OPTIONAL { ?id cim:GovHydroIEEE0.pmax ?pmax . }
  OPTIONAL { ?id cim:GovHydroIEEE0.pmin ?pmin . }
}
