#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovSteamFV2 .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovSteamFV2.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovSteamFV2.r ?r . }
  OPTIONAL { ?id cim:GovSteamFV2.t1 ?t1 . }
  OPTIONAL { ?id cim:GovSteamFV2.vamax ?vamax . }
  OPTIONAL { ?id cim:GovSteamFV2.vamin ?vamin . }
  OPTIONAL { ?id cim:GovSteamFV2.k ?k . }
  OPTIONAL { ?id cim:GovSteamFV2.t2 ?t2 . }
  OPTIONAL { ?id cim:GovSteamFV2.t3 ?t3 . }
  OPTIONAL { ?id cim:GovSteamFV2.pmax ?pmax . }
  OPTIONAL { ?id cim:GovSteamFV2.pmin ?pmin . }
  OPTIONAL { ?id cim:GovSteamFV2.t4 ?t4 . }
  OPTIONAL { ?id cim:GovSteamFV2.k1 ?k1 . }
  OPTIONAL { ?id cim:GovSteamFV2.k2 ?k2 . }
  OPTIONAL { ?id cim:GovSteamFV2.t5 ?t5 . }
  OPTIONAL { ?id cim:GovSteamFV2.k3 ?k3 . }
  OPTIONAL { ?id cim:GovSteamFV2.k4 ?k4 . }
  OPTIONAL { ?id cim:GovSteamFV2.iFlag ?iFlag . }
}
