#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovSteamSGO .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovSteamSGO.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovSteamSGO.r ?r . }
  OPTIONAL { ?id cim:GovSteamSGO.t1 ?t1 . }
  OPTIONAL { ?id cim:GovSteamSGO.vmax ?vmax . }
  OPTIONAL { ?id cim:GovSteamSGO.vmin ?vmin . }
  OPTIONAL { ?id cim:GovSteamSGO.t2 ?t2 . }
  OPTIONAL { ?id cim:GovSteamSGO.t3 ?t3 . }
  OPTIONAL { ?id cim:GovSteamSGO.t4 ?t4 . }
  OPTIONAL { ?id cim:GovSteamSGO.t5 ?t5 . }
  OPTIONAL { ?id cim:GovSteamSGO.t6 ?t6 . }
  OPTIONAL { ?id cim:GovSteamSGO.pmax ?pmax . }
  OPTIONAL { ?id cim:GovSteamSGO.pmin ?pmin . }
}
