#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:Pss1A .
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:Pss1A.inputSignalType ?inputSignalType . }
  OPTIONAL { ?id cim:Pss1A.a1 ?a1 . }
  OPTIONAL { ?id cim:Pss1A.a2 ?a2 . }
  OPTIONAL { ?id cim:Pss1A.ks ?ks . }
  OPTIONAL { ?id cim:Pss1A.t1 ?t1 . }
  OPTIONAL { ?id cim:Pss1A.t2 ?t2 . }
  OPTIONAL { ?id cim:Pss1A.t3 ?t3 . }
  OPTIONAL { ?id cim:Pss1A.t4 ?t4 . }
  OPTIONAL { ?id cim:Pss1A.t5 ?t5 . }
  OPTIONAL { ?id cim:Pss1A.t6 ?t6 . }
  OPTIONAL { ?id cim:Pss1A.tdelay ?tdelay . }
  OPTIONAL { ?id cim:Pss1A.vcl ?vcl . }
  OPTIONAL { ?id cim:Pss1A.vcu ?vcu . }
  OPTIONAL { ?id cim:Pss1A.vrmax ?vrmax . }
  OPTIONAL { ?id cim:Pss1A.vrmin ?vrmin . }
}
