#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:Pss2ST .
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:Pss2ST.inputSignal1Type ?inputSignal1Type . }
  OPTIONAL { ?id cim:Pss2ST.inputSignal2Type ?inputSignal2Type . }
  OPTIONAL { ?id cim:Pss2ST.k1 ?k1 . }
  OPTIONAL { ?id cim:Pss2ST.k2 ?k2 . }
  OPTIONAL { ?id cim:Pss2ST.t1 ?t1 . }
  OPTIONAL { ?id cim:Pss2ST.t2 ?t2 . }
  OPTIONAL { ?id cim:Pss2ST.t3 ?t3 . }
  OPTIONAL { ?id cim:Pss2ST.t4 ?t4 . }
  OPTIONAL { ?id cim:Pss2ST.t5 ?t5 . }
  OPTIONAL { ?id cim:Pss2ST.t6 ?t6 . }
  OPTIONAL { ?id cim:Pss2ST.t7 ?t7 . }
  OPTIONAL { ?id cim:Pss2ST.t8 ?t8 . }
  OPTIONAL { ?id cim:Pss2ST.t9 ?t9 . }
  OPTIONAL { ?id cim:Pss2ST.t10 ?t10 . }
  OPTIONAL { ?id cim:Pss2ST.lsmax ?lsmax . }
  OPTIONAL { ?id cim:Pss2ST.lsmin ?lsmin . }
}
