#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:PssELIN2 .
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:PssELIN2.apss ?apss . }
  OPTIONAL { ?id cim:PssELIN2.ks1 ?ks1 . }
  OPTIONAL { ?id cim:PssELIN2.ks2 ?ks2 . }
  OPTIONAL { ?id cim:PssELIN2.ppss ?ppss . }
  OPTIONAL { ?id cim:PssELIN2.psslim ?psslim . }
  OPTIONAL { ?id cim:PssELIN2.ts1 ?ts1 . }
  OPTIONAL { ?id cim:PssELIN2.ts2 ?ts2 . }
  OPTIONAL { ?id cim:PssELIN2.ts3 ?ts3 . }
  OPTIONAL { ?id cim:PssELIN2.ts4 ?ts4 . }
  OPTIONAL { ?id cim:PssELIN2.ts5 ?ts5 . }
  OPTIONAL { ?id cim:PssELIN2.ts6 ?ts6 . }
}
