#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:PssIEEE1A .
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:PssIEEE1A.inputSignalType ?inputSignalType . }
  OPTIONAL { ?id cim:PssIEEE1A.kx ?kx . }
  OPTIONAL { ?id cim:PssIEEE1A.t6 ?t6 . }
  OPTIONAL { ?id cim:PssIEEE1A.ks ?ks . }
  OPTIONAL { ?id cim:PssIEEE1A.t1 ?t1 . }
  OPTIONAL { ?id cim:PssIEEE1A.t2 ?t2 . }
  OPTIONAL { ?id cim:PssIEEE1A.t3 ?t3 . }
  OPTIONAL { ?id cim:PssIEEE1A.t4 ?t4 . }
  OPTIONAL { ?id cim:PssIEEE1A.t5 ?t5 . }
  OPTIONAL { ?id cim:PssIEEE1A.vsmax ?vsmax . }
  OPTIONAL { ?id cim:PssIEEE1A.vsmin ?vsmin . }
}
