#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:SynchronousMachineDetailed .
  OPTIONAL { ?id cim:SynchronousMachineDynamics.SynchronousMachine ?synchronousMachineId  . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.mBase ?mBase . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.damping ?damping . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.inertia ?inertia . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.statorLeakageReactance ?statorLeakageReactance . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.statorResistance ?statorResistance . }
  OPTIONAL { ?id cim:SynchronousMachineDetailed.ifdBaseType ?ifdBaseType . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.saturationFactor ?saturationFactor . }
  OPTIONAL { ?id cim:RotatingMachineDynamics.saturationFactor120 ?saturationFactor120 . }
}
