#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
    ?id rdf:type cim:VCompIEEEType1 .
    OPTIONAL { ?id cim:VoltageCompensatorDynamics.ExcitationSystemDynamics ?excitationSystemId . }
    OPTIONAL { ?id cim:VCompIEEEType1.tr   ?tr   . }
    OPTIONAL { ?id cim:VCompIEEEType1.rc ?rc . }
    OPTIONAL { ?id cim:VCompIEEEType1.xc ?xc . }
}
