#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:WindGenTurbineType3bIEC .
  OPTIONAL { ?id cim:RotatingMachineDynamics.RotatingMachine          ?synchronousMachineId    . }
  OPTIONAL { ?id cim:AsynchronousMachineDynamics.AsynchronousMachine  ?asynchronousMachineId   . }
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?excitationSystemId   . }
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:WindTurbineType3or4Dynamics.WindPlantDynamics     ?powerPlantId            . }
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.windContPType3IECId ?windContPType3IECId . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.windContQIECId ?windContQIECId . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.windMechIECId ?windMechIECId . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.windContCurrLimIECId ?windContCurrLimIECId . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.windProtectionIECId ?windProtectionIECId . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.fthres ?fthres . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.mwtcwp ?mwtcwp . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.tg ?tg . }
  OPTIONAL { ?id cim:WindGenTurbineType3bIEC.two ?two . }
}
