#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:WindContPitchAngleIEC .
  OPTIONAL { ?id cim:RotatingMachineDynamics.RotatingMachine          ?synchronousMachineId    . }
  OPTIONAL { ?id cim:AsynchronousMachineDynamics.AsynchronousMachine  ?asynchronousMachineId   . }
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?excitationSystemId   . }
  OPTIONAL { ?id cim:PowerSystemStabilizerDynamics.ExcitationSystemDynamics ?excitationSystemId . }
  OPTIONAL { ?id cim:WindTurbineType3or4Dynamics.WindPlantDynamics     ?powerPlantId            . }
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.dthetamax ?dthetamax . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.dthetamin ?dthetamin . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.kic ?kic . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.kiomega ?kiomega . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.kpc ?kpc . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.kpomega ?kpomega . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.kpx ?kpx . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.thetamax ?thetamax . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.thetamin ?thetamin . }
  OPTIONAL { ?id cim:WindContPitchAngleIEC.ttheta ?ttheta . }
}
